import { Poppins } from "next/font/google";
import "../styles/_globals.scss";
import HeadInfo from "@/component/HeadInfo";
import FooterInfo from "@/component/FooterInfo";

const inter = Poppins({
  weight: ['400', '600'],
  style: ['normal', 'italic'],
  subsets: ["latin"]
});

export const metadata = {
  title: "Company App",
  description: "Generated by Company app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className={inter.className}>
        <HeadInfo />
        {children}
        <FooterInfo />
      </body>
    </html>
  );
}
