import { Poppins } from "next/font/google";
import "./globals.css";
import HeadInfo from "@/component/HeadInfo";

const inter = Poppins({
  weight: ['400'],
  style: ['normal', 'italic'],
  subsets: ["latin"]
});

export const metadata = {
  title: "Company App",
  description: "Generated by Company app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className={inter.className}>
        <HeadInfo />
        {children}</body>
    </html>
  );
}
